-- 4-eyes un-onboard requests (requester OTP + approver email approval).

CREATE TABLE IF NOT EXISTS rhymedatapoem.s3_unonboard_request (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id INTEGER NOT NULL REFERENCES rhymedatapoem.s3_org(id),
    requester_user_id INTEGER NOT NULL,
    approver_user_id INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending_approval',
    expires_at TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_s3_unonboard_request_org_status
    ON rhymedatapoem.s3_unonboard_request (org_id, status);
