-- OTP challenges for sensitive admin actions (bcrypt-hashed codes, 10-minute TTL).

CREATE TABLE IF NOT EXISTS rhymedatapoem.s3_admin_otp (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    purpose VARCHAR(64) NOT NULL DEFAULT 'sensitive_action',
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_s3_admin_otp_user_purpose
    ON rhymedatapoem.s3_admin_otp (user_id, purpose);

CREATE INDEX IF NOT EXISTS ix_s3_admin_otp_expires_at
    ON rhymedatapoem.s3_admin_otp (expires_at);
