-- Email approve/reject tokens for sensitive admin actions (e.g. group delete with grants).

CREATE TABLE IF NOT EXISTS rhymedatapoem.s3_admin_approval (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purpose VARCHAR(64) NOT NULL,
    requester_user_id INTEGER NOT NULL,
    approver_user_id INTEGER NOT NULL,
    approve_token_hash VARCHAR(255) NOT NULL,
    reject_token_hash VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    expires_at TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_s3_admin_approval_purpose_status
    ON rhymedatapoem.s3_admin_approval (purpose, status);

CREATE INDEX IF NOT EXISTS ix_s3_admin_approval_expires_at
    ON rhymedatapoem.s3_admin_approval (expires_at);
